### ISSUE TITLE
При запуске тестового примера example проекта java-sdk-example возникает ошибка 70001 при вызове метода api. getInstrumentsService(). getTradableSharesSync() 

### ISSUE THREAD

**Issue by Binssmail** [Tinkoff/invest-api-java-sdk#17]
При выполнении метода возникает 70001, внутренняя ошибка сервиса

**Comment by hondasmx** [comment]
При возникновении ошибки в лог должен писаться tracking_id
Пришлите его, пожалуйста

**Comment by hondasmx** [comment]
Проблема возникает, если не указан токен
