### ISSUE TITLE
Возможно, опечатка в версии?

### ISSUE THREAD

**Issue by SimSonic** [Tinkoff/invest-api-java-sdk#27]
На странице документации:

![image](https://user-images.githubusercontent.com/2697754/179653890-16717b10-7495-4577-b73f-fb4ecbe3c0d2.png)

Релизный тег:

![image](https://user-images.githubusercontent.com/2697754/179653935-7140c360-ef20-4a72-9959-32cbef07543b.png)

В названии коммита и changelog-е:

![image](https://user-images.githubusercontent.com/2697754/179654176-a6c7a0ff-ddf9-4eb3-a2b4-75a738338270.png)

В Maven Central:

![image](https://user-images.githubusercontent.com/2697754/179653822-26290c42-bc28-4c34-ada1-ebf4d78af02d.png)

Как всё-таки должно было быть? `1.0-M10` или `1.0.M10` или `1.0-10` или `1.0.10`?

Скорее всего, нужно либо обновить документацию, либо перепушить тег / сборку в mvnrepository.

Спасибо 🙃

**Comment by hondasmx** [comment]
Добрый день!
Прошу прощения за путаницу в версиях. Верная версия - 1.0.10
