### ISSUE TITLE
java.lang.ClassNotFoundException: io.grpc.ClientStreamTracer$InternalLimitedInfoFactory

### ISSUE THREAD

**Issue by sergey-klochkov** [Tinkoff/invest-api-java-sdk#3]
https://github.com/Tinkoff/invest-api-java-sdk/blob/9c50758afe1a0b14442125776d5569990c2abe09/contract/pom.xml#L39
https://github.com/Tinkoff/invest-api-java-sdk/blob/9c50758afe1a0b14442125776d5569990c2abe09/contract/pom.xml#L57

Разные версии библиотек и генератора grpc приводят к ClassNotFound

**Comment by zlumyo** [comment]
Спасибо, что подметили!

**Comment by zolotarev-om** [comment]
Столкнулся с ошибкой такого же рода 
`java.lang.NoClassDefFoundError: io/grpc/ClientStreamTracer$InternalLimitedInfoFactory`
будет ли выложена в maven исправленная версия?

**Comment by sergey-klochkov** [comment]
соберите версию из главной ветки и залейти в локальный репозиторий

> Столкнулся с ошибкой такого же рода `java.lang.NoClassDefFoundError: io/grpc/ClientStreamTracer$InternalLimitedInfoFactory` будет ли выложена в maven исправленная версия?

**Comment by zlumyo** [comment]
@zolotarev-om готовится к выходу версия с исправлением

**Comment by gunkins** [comment]
@zlumyo в новой версии все еще та же ошибка

**Comment by gunkins** [comment]
@zlumyo Подскажите, пожалуйста, когда ожидается релиз рабочей версии с исправленными версиями?
