### ISSUE TITLE
Способ работы с песочницей

### ISSUE THREAD

**Issue by fowork1** [Tinkoff/invest-api-java-sdk#43]
Здравствуйте. 
В документации написано: 
"Для работы с песочницей существуют два способа:

1. Все вызовы сервиса песочницы выполняются по адресу sandbox-invest-public-api.tinkoff.ru:443.
2. Пользоваться методами Sandbox-сервиса.

Команда TINKOFF INVEST API рекомендует пользоваться первым способом."

Я правильно понимаю, что это разные способы?
Как воспользоваться первым способом через ваш SDK?
Достаточно ли просто использовать ключ созданный для SandBox?
Спасибо.

**Comment by fowork1** [comment]
Сюда же.
Почему обычные метод и метод из песочницы имеют разную сигнатуру?
```
// Возвращает Portfolio
api.operationsService.getPortfolioSync(account.id)
```

**Comment by fowork1** [comment]
Так же, не удаётся найти метод (использую "ru.tinkoff.piapi:java-sdk-core:1.3"), проверял и в исходниках класса
```
api.sandboxService.GetSandboxWithdrawLimits
```
хотя он описан и в [документации](https://tinkoff.github.io/investAPI/sandbox/#getsandboxwithdrawlimits) и в [свагере](https://tinkoff.github.io/investAPI/swagger-ui/#/SandboxService/SandboxService_GetSandboxWithdrawLimits)

**Comment by pechenkinea** [comment]
для песочницы можно так:
```
InvestApi sandboxApi = InvestApi.createSandbox(getToken());
...
investApi.getOperationsService().getPortfolioSync(account.getId())
```

**Comment by fowork1** [comment]
@pechenkinea 
Извините, не очень понял ваш ответ...

В настоящее время, я создаю песочный аккаунт и пополняю его
```kotlin
var api = InvestApi.create(TOKEN);

val sand = api.sandboxService
sand.openAccountSync()
var account = sand.accountsSync.get(0)
val money = MoneyValue.newBuilder().setUnits(10_000).setCurrency("RUB").build()
sand.payInSync(account.id, money)
```
И вот дальше возникает проблема получения баланса, которую я описывал выше.
Про отсутствие метода GetSandboxWithdrawLimits

По вашему ответу возникает нестыковка:
Если использовать investApi и передавать в метод getPortfolioSync песочный аккаунт, то будет ошибка, что счёт не найден.
Если передавать реальный, то будет работа с реальным аккаунтом, а не в песочнице.
Если использовать sandboxApi, то нет метода getPortfolioSync.

Я очень благодарен за ваш ответ, но поясните его пожалуйста

**Comment by pechenkinea** [comment]
InvestApi.createSandbox(TOKEN); - песочница
InvestApi.create(TOKEN); - бой

*при создании песочницы надо еще открыть счет.  но каждый раз при старте приложения создавать его не обязательно. в Вашей песочнице он остается (но, судя по документации, тинькофф может в любой момент его удалить)

**Comment by fowork1** [comment]
> InvestApi.createSandbox(TOKEN); - песочница InvestApi.create(TOKEN); - бой
> 
> *при создании песочницы надо еще открыть счет. но каждый раз при старте приложения создавать его не обязательно. в Вашей песочнице он остается (но, судя по документации, тинькофф может в любой момент его удалить)

Да. И... 
Не могли бы вы продолжить мысль, а то пока не отвечает на вопросы

**Comment by pechenkinea** [comment]
делаем песочницу InvestApi.createSandbox(TOKEN);  и дальше работаем с обычными, не песочными методами.
Конечно они не все поддерживаются, но все же лучше чем писать разный код для песочницы и для боя

**Comment by fowork1** [comment]
@pechenkinea 
Да, спасибо большое, такой подход удобней. Жаль, что я не видел его в документации.

**Comment by AlexanderVolkovTCS** [comment]
>Конечно они не все поддерживаются

в ближайшем релизе добавим часть недостающих методов песочницы 

>Жаль, что я не видел его в документации.

Спасибо, дополним
