### ISSUE TITLE
Не работает отписка от стрима .unsubscribeLastPrices

### ISSUE THREAD

**Issue by GavryushkinSI** [Tinkoff/invest-api-java-sdk#45]
MarketDataSubscriptionService service = api.getMarketDataStreamService().getStreamById(..);
service.unsubscribeLastPrices(...);

**Comment by GavryushkinSI** [comment]
При вызове метода unsubscribeLastPrices и дальнейшем вызове api.getMarketDataStreamService().getStreamById(..) стрим не исчезает

**Comment by hondasmx** [comment]
При отписке от бумаг вы не прерываете стрим, а всего лишь говорите bidirectional стриму, что вы больше не хотите получать информацию
Если не осталось подписок на бумаги - вы будете получать ping пакеты каждые несколько минут
