### ISSUE TITLE
В апи не реализован доступ к методу GetInstrumentBy

### ISSUE THREAD

**Issue by dvalyaev** [Tinkoff/invest-api-java-sdk#46]
В апи не реализован доступ к методу GetInstrumentBy, приходится дергать FindInstrument - а он возвращает пустой список для currency, например 5fe6df61-6c55-45f2-a505-d17e8e2a5bc9

**Comment by AlexanderVolkovTCS** [comment]
В API метод есть, а в java sdk он разбит на методы getInstrumentByTickerSync, getInstrumentByUidSync и тд

**Comment by dvalyaev** [comment]
Действительно в sdk есть публичный метод 
getInstrumentByTickerSync(@Nonnull String ticker, @Nonnull String classCode)
но аналогичного метода getInstrumentByUidSync - нет
есть только приватный 
https://github.com/Tinkoff/invest-api-java-sdk/blob/main/core/src/main/java/ru/tinkoff/piapi/core/InstrumentsService.java#L1485

**Comment by hondasmx** [comment]
Есть подобные методы
- getCurrencyByUidSync
- getFutureByUidSync

Это то, что вы ищете?

**Comment by dvalyaev** [comment]
когда я достаю историю операций и хочу посмотреть информацию об инструменте, то гораздо удобнее дернуть общий метод getInstrumentByUidSync, чем писать портянку с ифами и для каждого типа инструмента дергать свой отдельный метод
