### ISSUE TITLE
Не приходят данные по подписке

### ISSUE THREAD

**Issue by KachkoBart** [Tinkoff/invest-api-java-sdk#47]
```
StreamProcessor<MarketDataResponse> processor = response -> {
            if (response.hasCandle()) {
                log.info("Новые данные по свечам: {}", response);
            } else if (response.hasSubscribeCandlesResponse()) {
                var successCount = response.getSubscribeCandlesResponse().getCandlesSubscriptionsList().stream().filter(el -> el.getSubscriptionStatus().equals(SubscriptionStatus.SUBSCRIPTION_STATUS_SUCCESS)).count();
                var errorCount = response.getSubscribeTradesResponse().getTradeSubscriptionsList().stream().filter(el -> !el.getSubscriptionStatus().equals(SubscriptionStatus.SUBSCRIPTION_STATUS_SUCCESS)).count();
                log.info("удачных подписок на свечи: {}", successCount);
                log.info("неудачных подписок на свечи: {}", errorCount);
            }
        };
        Consumer<Throwable> onErrorCallback = error -> log.error(error.toString());
        marketDataStreamService.newStream("candles_stream", processor, onErrorCallback).subscribeCandles(List.of(figi));
```
Сделал как в примере, но после запуска приложение не встает в режим ожидания, а завершается. Проверял, когда биржа работала и инструмент был доступен для торгов.

**Comment by KachkoBart** [comment]
может ли быть проблема в том, что я использовал песочницу?

**Comment by SRadyukov** [comment]
вы используете асинхронное api которое не переводит в режим ожидания и не блокируется.
вы можете сделать Thread.sleep в управляющем потоке, или например сигнал c помощью [CountDownLatch](https://docs.oracle.com/javase/7/docs/api/java/util/concurrent/CountDownLatch.html)
`
int  N = 1000;
CountDownLatch doneSignal = new CountDownLatch(N);
StreamProcessor<MarketDataResponse> processor = response -> {
  log.info("message: {}", response);
  doneSignal. countDown();
};
Consumer<Throwable> onErrorCallback = error -> log.error(error.toString());
marketDataStreamService.newStream("candles_stream", processor, onErrorCallback).subscribeCandles(List.of(figi));
doneSignal.await(); //wait to N count
`

**Comment by AlexanderVolkovTCS** [comment]
спасибо @SRadyukov, @KachkoBart если будут вопросы - переоткройте тикет.
