### ISSUE TITLE
нет figi в getOrdersSync

### ISSUE THREAD

**Issue by pechenkinea** [Tinkoff/invest-api-java-sdk#48]
не заполнен figi в ответе на
```
investApi.getOrdersService().getOrdersSync(account.getId())
```

**Comment by AlexanderVolkovTCS** [comment]
Добрый день, по какому instrument_uid?

Например, у опционов вообще нет figi.

**Comment by pechenkinea** [comment]
проверял на акциях (investApi - песочница)

**Comment by hondasmx** [comment]
Спасибо за репорт
поправим в ближайшем релизе
