### ISSUE TITLE
Отписка от стрима свечи

### ISSUE THREAD

**Issue by kusakinsv** [Tinkoff/invest-api-java-sdk#6]
Уважаемый **zlumyo**, подскажи, пожалуйста, как отписаться от стрима свечи. Поток блокируется, а по приведенному примеру в Example не получается.

**Comment by hondasmx** [comment]
Добавили новое API для работы со стримами.
https://github.com/Tinkoff/invest-api-java-sdk/blob/main/example/src/main/java/ru/tinkoff/piapi/example/Example.java#L138
