### ISSUE TITLE
Native image compatibility

### ISSUE THREAD

**Issue by zscauer** [Tinkoff/invest-api-java-sdk#61]
Был ли у кого нибудь успешный опыт сборки native image приложения с данным sdk?
Пробовал собрать spring и quarkus (все последней версии), но не получается собрать из-за библиотеки
`io.grpc:grpc-netty-shaded`.

Во время сборки возникают ошибки относительно различных классов вроде этой:
```
Caused by: com.oracle.graal.pointsto.constraints.UnresolvedElementException:
Discovered unresolved type during parsing: org.apache.log4j.Logger.
This error is reported at image build time because class io.grpc.netty.shaded.io.netty.util.internal.logging.Log4JLoggerFactory is registered for linking at image build time by command line
```
Попытки проинициализировать проблемные классы в runtime вместо buildtime безуспешны.

**Comment by Dankosik** [comment]
Да, попробоуй закинуть в BP_NATIVE_IMAGE_BUILD_ARGUMENTS  --initialize-at-build-time=ch.qos.logback,org.slf4j.LoggerFactory
Также подключи библиотечку com.google.cloud:native-image-support:0.14.1 они там что-то с netty фиксили

**Comment by Dankosik** [comment]
У меня sring boot - 3.1.0
springCloud - 2022.0..2
И версия плагина для graalVM native image  id("org.graalvm.buildtools.native") version "0.9.22"
dependencies{
    implementation("com.google.cloud:native-image-support:0.14.1")
}
tasks.withType<org.springframework.boot.gradle.tasks.bundling.BootBuildImage> {
    environment.put("BP_NATIVE_IMAGE_BUILD_ARGUMENTS","--no-fallback --initialize-at-build-time=ch.qos.logback,org.slf4j.LoggerFactory," +
            "org.slf4j.simple.SimpleLogger,org.slf4j.impl.StaticLoggerBinder,org.slf4j.MDC" +
            " -J-Dfile.encoding=UTF-8"
    )
}
Запускаю билд командой ./gradlew bootBuildImage
При чем io.grpc:grpc-netty-shaded:1.44.0 тянется в зависимости, но такой ошибки не ловил
Были какие-то другие с netty, но они пофиксились implementation("com.google.cloud:native-image-support:0.14.1") этим

**Comment by Dankosik** [comment]
А у тебя подключено?
`implementation("org.springframework.boot:spring-boot-starter-webflux")`
Может спринговкие зависимости на netty как-то перезатирают `io.grpc:grpc-netty-shaded`

**Comment by zscauer** [comment]
я без клауда, но это решение `--initialize-at-build-time=ch.qos.logback,org.slf4j.LoggerFactory,org.slf4j.simple.SimpleLogger,org.slf4j.impl.StaticLoggerBinder,org.slf4j.MD`плюс гугловая либа вроде решило проблему, большое спасибо @Dankosik!
На днях оформлю в PR.
